apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: colour-my-change
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: colour-my-change
    spec:
      containers:
      - name: colour-my-change
        image: gcr.io/radical-sloth/colour-my-change:1.0.7
        ports:
        - containerPort: 5000
