apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: colour-your-change
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: colour-your-change
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
