apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: colour-my-change
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: colour-my-change
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90
